### ISSUE TITLE
[Space] MetaMask issues

### ISSUE THREAD

**Issue by robertu7** [thematters/thespace-landing-page#91]
## Issues
* [iOS][Deeplink] Sign In with MetaMask using WalletConnect will jump into App Store;
* [Network] Switch to custom network (Polygon) is unsupported in MetaMask built-in browser if user hasn't added custom network;

## Discussions
* https://mattersnews.slack.com/archives/GGHTVNTA7/p1654465150599729
* https://mattersnews.slack.com/archives/C03869USZL5/p1654891010595259?thread_ts=1654665506.409199&cid=C03869USZL5

## Refs
* https://github.com/MetaMask/metamask-mobile/issues/3965
* https://github.com/WalletConnect/walletconnect-monorepo/issues/444

**Comment by robertu7** [comment]
> Is it for Matters.News or TheSpace, or both?

These issues are shared on both, but we can start fixing from matters.news.

**Comment by robertu7** [comment]
@Jasmine-liang I added two Slack discussions link, please check them out.

**Comment by Jasmine-liang** [comment]
[Support for switching network on metamask mobile](https://github.com/tmm/wagmi/discussions/405) is added in ^0.5 version.

**Comment by Jasmine-liang** [comment]
[iOS][Deeplink]: For now this issue is still not fixed by [WalletConnect](https://github.com/WalletConnect/walletconnect-monorepo/issues?q=is%3Aissue+is%3Aopen+universal+links). 
We could still guide users to open Metamask through WalletConnect properly, discussed [here](https://discord.com/channels/920891282161819698/981498760846798918/994593312650579968) with community member Denken :)

**Comment by devformatters** [comment]
@Jasmine-liang 
Feel free to break this into smaller tasks, and drop new issues in `Upcoming Sprint`.

cc @robertu7
